### ISSUE TITLE
Criar nova logo

### ISSUE THREAD

**Issue by gdcmarinho** [gdcmarinho/links-uteis#137]

**Comment by andre2l2** [comment]
A logo está ótima! 

O problema é que é preta, e quem estiver usando o github com o tema escuro não da para ver muito bem. Seria bem bacana manter a logo preto com um fundo banco, aí independente do tema que estiver usando não vai afetar a visualização.

**Comment by gdcmarinho** [comment]
@andre2l2 concordo com você. Talvez uma logo colorida faça mais sentido do que colocar um fundo. O que acha?

**Comment by andre2l2** [comment]
Acho que seria uma boa!! Ficaria bem bacana! Tem algo me mente já?

**Comment by gdcmarinho** [comment]
@andre2l2 pra ser sincero, ainda não. Vou começar a rabiscar algo em breve no Figma para ver o que pode sair. Tem alguma sugestão ou inspiração em que eu possa usar?

**Comment by Nerd00F** [comment]
![images](https://user-images.githubusercontent.com/42983463/159106521-f1d6cdf1-8b13-4282-9b45-870b4c1e9199.jpeg)

Que tal está, @gdcmarinho?

**Comment by Nerd00F** [comment]
Se gostou, me fala qual das três, que eu já escrevo "Links Úteis" e coloco no repo

**Comment by gdcmarinho** [comment]
> ![images](https://user-images.githubusercontent.com/42983463/159106521-f1d6cdf1-8b13-4282-9b45-870b4c1e9199.jpeg)
> 
> Que tal está, @gdcmarinho?

Nenhuma delas. Parece logo de template.

**Comment by Nerd00F** [comment]
Talvez pode pintar a que já tem com tom de verde para ficar mais visível, tanto em tema claro quanto escuro

**Comment by gdcmarinho** [comment]
Não sei. Irei verificar aqui se ainda tenho o modelo que utilizei e crio uma nova versão.

**Comment by Nerd00F** [comment]
ok, me mantenha informado

**Comment by Nerd00F** [comment]
@gdcmarinho 

Ficou legal a logo, pode fechar essa issue?

**Comment by gdcmarinho** [comment]
@Nerd00F pode fechar sim. Eu ainda acho que vou fazer algumas alterações futuramente, mas por hora, vamos usar essa como base.

**Comment by Nerd00F** [comment]
Ok
